import { codeUrl, demoUrl } from './constants.js';


export const iTasks = [
  {
    id: 1,
    maxScore: 6,
    score: '-',
    title: 'Rectangle & Round',
    description: 'JavaScript',
    codePath: codeUrl + 'i1_rectangle_round/',
    demoPath: demoUrl + 'i1_rectangle_round/',
  },
  {
    id: 2,
    maxScore: '-',
    score: '-',
    title: 'Stepper (Wizard)',
    description: 'JavaScript',
    codePath: codeUrl + 'i2_stepper_react/',
    demoPath: demoUrl + 'i2_stepper_react/',
  },
  {
    id: 3,
    maxScore: 4,
    score: 3.5,
    title: 'News',
    description: 'JavaScript',
    codePath: codeUrl + 'i3_news/',
    demoPath: demoUrl + 'i3_news/',
  },
  {
    id: 4,
    maxScore: 4,
    score: 3,
    title: 'Line Chart',
    description: 'JavaScript',
    codePath: codeUrl + 'i4_chart',
    demoPath: demoUrl + 'i4_chart',
  },
  {
    id: 5,
    maxScore: '6',
    score: '-',
    title: 'Image Crop',
    description: 'JavaScript',
    codePath: codeUrl + 'i5_crop',
    demoPath: demoUrl + 'i5_crop',
  },
  {
    id: 6,
    maxScore: 5,
    score: 5,
    title: 'News',
    description: 'React',
    codePath: codeUrl + 'i6_news_react/',
    demoPath: demoUrl + 'i6_news_react/',
  },
  {
    id: 7,
    maxScore: '-',
    score: '-',
    title: 'Stepper (Wizard)',
    description: 'React',
    codePath: codeUrl + 'i7_stepper_react/',
    demoPath: demoUrl + 'i7_stepper_react/',
  },
  {
    id: 8,
    maxScore: '-',
    score: '-',
    title: 'News',
    description: 'React, TypeScript',
    codePath: codeUrl + 'i8_news_react_ts/',
    demoPath: demoUrl + 'i8_news_react_ts/',
  },
  {
    id: 9,
    maxScore: '-',
    score: '-',
    title: 'Stepper',
    description: 'React, TypeScript',
    codePath: codeUrl + 'i9_stepper_react_typescript/',
    demoPath: demoUrl + 'i9_stepper_react_typescript/',
  },
];
